using ERP.NSQuell.Models.ViewModels.Almacen;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Security.Claims;

namespace ERP.NSQuell.Controllers;

public sealed class AlmacenComprasController : Controller
{
    private readonly IConfiguration _configuration;
    public AlmacenComprasController(IConfiguration configuration)=>_configuration=configuration;
    private string ConnectionString=>_configuration.GetConnectionString("DefaultConnection")??throw new InvalidOperationException("No se encontro DefaultConnection.");
    private int UsuarioID=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("UsuarioID"),out var id)?id:0;
    [HttpGet] public async Task<IActionResult> Confirmar(string modulo,int catalogoID,string? variante,string? returnUrl,CancellationToken ct){var vm=new AlmacenCompraVm{Modulo=modulo.Trim().ToUpperInvariant(),CatalogoID=catalogoID,Variante=variante??"",ReturnUrl=returnUrl};await using var cn=new SqlConnection(ConnectionString);await cn.OpenAsync(ct);if(vm.Modulo=="MP"){const string sql=@"SELECT Codigo,Nombre,StockMinimo,StockAviso,N'KG' Unidad,(SELECT ISNULL(SUM(CASE WHEN TipoMovimiento IN(N'Entrada',N'Retorno',N'Ajuste',N'AjustePositivo') THEN Cantidad ELSE -Cantidad END),0) FROM dbo.AlmacenMP_Movimientos WHERE MaterialID=m.MaterialID AND Activo=1 AND ISNULL(NULLIF(UPPER(TipoMP),N''),N'VIRGEN')=@Variante) Stock FROM dbo.ERP_Materiales m WHERE MaterialID=@Id AND Activo=1";await CargarAsync(cn,sql,vm,ct);}else{const string sql=@"SELECT e.Codigo,e.Nombre,e.StockMinimo,e.StockAviso,e.UnidadDefault Unidad,ISNULL(v.Saldo,0) Stock FROM dbo.ERP_Embalajes e LEFT JOIN dbo.vw_AlmacenEmbalajesInventario v ON v.EmbalajeID=e.EmbalajeID WHERE e.EmbalajeID=@Id AND e.Activo=1";await CargarAsync(cn,sql,vm,ct);}return View(vm);}
    [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Confirmar(AlmacenCompraVm model,CancellationToken ct){await using var cn=new SqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new SqlCommand("dbo.sp_Almacen_SolicitarCompra",cn){CommandType=CommandType.StoredProcedure};cmd.Parameters.Add("@Modulo",SqlDbType.NVarChar,20).Value=model.Modulo;cmd.Parameters.Add("@CatalogoID",SqlDbType.Int).Value=model.CatalogoID;cmd.Parameters.Add("@Variante",SqlDbType.NVarChar,30).Value=string.IsNullOrWhiteSpace(model.Variante)?DBNull.Value:model.Variante;cmd.Parameters.Add("@UsuarioID",SqlDbType.Int).Value=UsuarioID>0?UsuarioID:DBNull.Value;cmd.Parameters.Add("@EsAutomatica",SqlDbType.Bit).Value=false;cmd.Parameters.Add("@Motivo",SqlDbType.NVarChar,500).Value=string.IsNullOrWhiteSpace(model.Motivo)?DBNull.Value:model.Motivo;var output=cmd.Parameters.Add("@SolicitudCompraID",SqlDbType.Int);output.Direction=ParameterDirection.Output;try{await cmd.ExecuteNonQueryAsync(ct);TempData["AlmacenOk"]=$"Solicitud enviada a Compras. Folio interno #{output.Value}.";}catch(Exception ex){TempData["AlmacenError"]=ex.Message;}return LocalRedirect(string.IsNullOrWhiteSpace(model.ReturnUrl)?Url.Action("Index","Almacen")!:model.ReturnUrl);}
    private static async Task CargarAsync(SqlConnection cn,string sql,AlmacenCompraVm vm,CancellationToken ct){await using var cmd=new SqlCommand(sql,cn);cmd.Parameters.Add("@Id",SqlDbType.Int).Value=vm.CatalogoID;cmd.Parameters.Add("@Variante",SqlDbType.NVarChar,20).Value=string.Equals(vm.Variante,"MOLIDO",StringComparison.OrdinalIgnoreCase)?"MOLIDO":"VIRGEN";await using var rd=await cmd.ExecuteReaderAsync(ct);if(!await rd.ReadAsync(ct))throw new InvalidOperationException("No se encontro el articulo.");vm.Codigo=Convert.ToString(rd["Codigo"])??"";vm.Descripcion=Convert.ToString(rd["Nombre"])??"";vm.StockMinimo=Convert.ToDecimal(rd["StockMinimo"]);vm.StockAviso=Convert.ToDecimal(rd["StockAviso"]);vm.Stock=Convert.ToDecimal(rd["Stock"]);vm.Unidad=Convert.ToString(rd["Unidad"])??"";}
}
